site_name: DivaDocs
site_url: https://flipleerr.github.io/divadocs/
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
theme:
  name: material
  palette:
    scheme: slate
